#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

ln constant/controlProperties 0/include/controlProperties
ln constant/transportProperties 0/include/transportProperties

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

setResults()
{
	value=$(sed -En 's/maxPot[[:blank:]]+//p' constant/controlProperties | sed 's/;.*//') 
	sed -E '/Vcell/s/[^[:blank:]]+$/'"$value;"/ -i constant/Results
}


\cp 0/rho_i.orig 0/rho_i
\cp 0/T.orig 0/T

runApplication blockMesh

#Set dictionaries
setResults

#runApplication setFields

#-- Run on single processor

runApplication $(getApplication)

postProcess -func partialCurrentDensity -noZero #-latestTime

paraFoam -builtin
#------------------------------------------------------------------------------
